const skin = {
  aside_white_nav_white: {
    className: "aside_white_nav_white",
    asideBackground: "#ffffff",
    asideColor: "#000000",
    logoBackground: "#ffffff",
    logoColor: "#000000",
    navBackground: "#ffffff",
    navColor: "#000000",
    activeColor: "#409EFF",
  },
  aside_black_nav_white: {
    className: "aside_black_nav_white",
    asideBackground: "#222d32",
    asideColor: "#ffffff",
    logoColor: "#ffffff",
    logoBackground: "#222d32",
    navBackground: "#ffffff",
    navColor: "#000000",
    activeColor: "#409EFF",
  },
  aside_white_nav_black: {
    className: "aside_white_nav_black",
    asideBackground: "#ffffff",
    asideColor: "#000000",
    logoColor: "#ffffff",
    logoBackground: "#222d32",
    navBackground: "#222d32",
    navColor: "#ffffff",
    activeColor: "#409EFF",
  },
  aside_purple_nav_white: {
    className: "aside_purple_nav_white",
    asideBackground: "#605ca8",
    asideColor: "#ffffff",
    logoColor: "#ffffff",
    logoBackground: "#605ca8",
    navBackground: "#ffffff",
    navColor: "#000000",
    activeColor: "#409EFF",
  },
};
export default skin;
