const skin = {
  aside_white_nav_white: {
    className: "aside_white_nav_white",
    asideBackground: "#ffffff",
    asideColor: "#000000",
    logoBackground: "#ffffff",
    logoColor: "#000000",
    navBackground: "#ffffff",
    navColor: "#000000",
    activeColor: "var(--el-color-primary)",
  },
  aside_black_nav_white: {
    className: "aside_black_nav_white",
    asideBackground: "#222d32",
    asideColor: "#ffffff",
    logoColor: "#ffffff",
    logoBackground: "#222d32",
    navBackground: "#ffffff",
    navColor: "#000000",
    activeColor: "var(--el-color-primary)",
  },
  aside_white_nav_black: {
    className: "aside_white_nav_black",
    asideBackground: "#ffffff",
    asideColor: "#000000",
    logoColor: "#ffffff",
    logoBackground: "#222d32",
    navBackground: "#222d32",
    navColor: "#ffffff",
    activeColor: "var(--el-color-primary)",
  },
  aside_purple_nav_white: {
    className: "aside_purple_nav_white",
    asideBackground: "#605ca8",
    asideColor: "#ffffff",
    logoColor: "#ffffff",
    logoBackground: "#605ca8",
    navBackground: "#ffffff",
    navColor: "#000000",
    activeColor: "var(--el-color-primary)",
  },
  aside_yellow_nav_white: {
    className: "aside_yellow_nav_white",
    asideBackground: "#f39c12",
    asideColor: "#ffffff",
    logoColor: "#ffffff",
    logoBackground: "#f39c12",
    navBackground: "#ffffff",
    navColor: "#000000",
    activeColor: "var(--el-color-primary)",
  },
  aside_white_nav_yellow: {
    className: "aside_white_nav_yellow",
    asideBackground: "#ffffff",
    asideColor: "#000000",
    logoColor: "#ffffff",
    logoBackground: "#f39c12",
    navBackground: "#f39c12",
    navColor: "#ffffff",
    activeColor: "var(--el-color-primary)",
  },
};
export default skin;
